FROM node:20-slim

RUN apt-get update && apt-get install -y curl git && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
COPY server/package*.json ./server/
COPY client/package*.json ./client/

RUN npm install --workspaces

COPY . .

# version.json is generated by CI before Docker build (see deploy.yml)
# Fallback: if missing, create a stub so the app doesn't crash
RUN test -f version.json || echo '{"build":0,"commit":"local","buildTime":"unknown"}' > version.json

# Build the client
RUN cd client && npm run build

RUN chmod +x start.sh

ENV PORT=8080

EXPOSE 8080

CMD ["./start.sh"]
